import { library } from '@fortawesome/fontawesome-svg-core'
import {
    faCircleHalfStroke,
    faMoon,
    faSun,
    faUserSecret,
    faIdBadge,
    faUser,
    faAt,
    faKey,
    faAngleDown,
    faSignOut,
    faUserEdit,
    faGauge,
    faExclamationTriangle,
    faAngleDoubleLeft,
    faAngleDoubleRight,
    faMagnifyingGlass,
    faXmark,
    faFolderPlus,
    faHeading,
    faTags,
    faUpRightFromSquare,
    faNewspaper,
    faPenToSquare,
    faRotateLeft,
    faTrash,
    faCircleCheck,
    faCircleExclamation,
    faCircleXmark,
    faEye,
    faLock,
    faThumbsUp,
    faThumbsDown,
} from '@fortawesome/free-solid-svg-icons'

function init_icons() {
    library.add(
        faUserSecret,
        faCircleHalfStroke,
        faMoon,
        faSun,
        faIdBadge,
        faUser,
        faAt,
        faKey,
        faAngleDown,
        faSignOut,
        faUserEdit,
        faGauge,
        faExclamationTriangle,
        faAngleDoubleLeft,
        faAngleDoubleRight,
        faMagnifyingGlass,
        faXmark,
        faFolderPlus,
        faHeading,
        faTags,
        faUpRightFromSquare,
        faNewspaper,
        faPenToSquare,
        faRotateLeft,
        faTrash,
        faCircleCheck,
        faCircleExclamation,
        faCircleXmark,
        faEye,
        faLock,
        faThumbsUp,
        faThumbsDown,
    )
}

export { init_icons }